server: 
  port: 8080

---
spring.profiles: dev

api:
 idle:
  read-timeout: 8000 
  write-timeout: 8000
  all-idle-timeout: 8000
 auth: 
  url: https://allianz-auth-srv.cfapps.io
  read-timeout: 5000 
  write-timeout: 5000
  connection-timeout: 5000
 person: 
  url: https://allianz-person-srv.cfapps.io
  read-timeout: 5000
  write-timeout: 5000 
  connection-timeout: 5000